//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Турагенство.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Турагенство.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000_cute_travel_icons_pattern_for_target_by_steph_calvert_art {
            get {
                object obj = ResourceManager.GetObject("000-cute-travel-icons-pattern-for-target-by-steph-calvert-art", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1686048626713 {
            get {
                object obj = ResourceManager.GetObject("1686048626713", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap australia_icons_set_sketch_for_your_design_vector_13793285 {
            get {
                object obj = ResourceManager.GetObject("australia-icons-set-sketch-for-your-design-vector-13793285", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document2 {
            get {
                object obj = ResourceManager.GetObject("document2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e91564445f0e09918718f170d290b4d1_png_wh300 {
            get {
                object obj = ResourceManager.GetObject("e91564445f0e09918718f170d290b4d1.png_wh300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gratis_png_documento_contrato_firma_certificacion_plagio_thumbnail {
            get {
                object obj = ResourceManager.GetObject("gratis-png-documento-contrato-firma-certificacion-plagio-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gratis_png_documento_contrato_firma_certificacion_plagio_thumbnail1 {
            get {
                object obj = ResourceManager.GetObject("gratis-png-documento-contrato-firma-certificacion-plagio-thumbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoza_ru__1_ {
            get {
                object obj = ResourceManager.GetObject("logoza.ru (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoza_ru__1__QWrMJ843M_transformed {
            get {
                object obj = ResourceManager.GetObject("logoza_ru_(1)-QWrMJ843M-transformed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoza_ru__1__xwONzlhrGd_transformed {
            get {
                object obj = ResourceManager.GetObject("logoza_ru_(1)-xwONzlhrGd-transformed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoza1 {
            get {
                object obj = ResourceManager.GetObject("logoza1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoza2 {
            get {
                object obj = ResourceManager.GetObject("logoza2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lovepik_beauty_beach_holiday_png_image_400379427_wh300 {
            get {
                object obj = ResourceManager.GetObject("lovepik-beauty-beach-holiday-png-image_400379427_wh300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_chief_executive_computer_icons_businessperson_business_people_logo_monochrome_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-chief-executive-computer-icons-businessperson-business-people-log" +
                        "o-monochrome-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_coconut_tree_phi_phi_islands_eleuthera_palm_trees_leaf_palm_tree_arecaceae_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-coconut-tree-phi-phi-islands-eleuthera-palm-trees-leaf-palm-tree-" +
                        "arecaceae-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_necktie_suit_costume_formal_wear_men_s_decorative_blue_tie_suit_blue_decorative_christmas_decoration_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-necktie-suit-costume-formal-wear-men-s-decorative-blue-tie-suit-b" +
                        "lue-decorative-christmas-decoration-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_project_management_body_of_knowledge_project_manager_executive_manager_businessmanatdesk_angle_business_recruitment_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-project-management-body-of-knowledge-project-manager-executive-ma" +
                        "nager-businessmanatdesk-angle-business-recruitment-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_coconut_tree_png_image_4309318 {
            get {
                object obj = ResourceManager.GetObject("pngtree-coconut-tree-png-image_4309318", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Вход {
            get {
                object obj = ResourceManager.GetObject("Вход", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок_экрана_2023_06_10_190513 {
            get {
                object obj = ResourceManager.GetObject("Снимок экрана 2023-06-10 190513", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок_экрана_2023_06_10_1905131 {
            get {
                object obj = ResourceManager.GetObject("Снимок экрана 2023-06-10 1905131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
